In [1]:
from generator_based_on_Seattle import *

In [2]:
from parameters import *

In [ ]:
from pathlib import Path

parent_folder: str = 'generated_traffic_data'
load_folder_path: str = parent_folder + '/' + 'load' + '_' + str(LAMBDA_0)
actual_traffic_folder_path: str = load_folder_path + '/' + 'actual_traffic'
predicted_traffic_folder_path: str = load_folder_path + '/' + 'predicted_traffic'
predicted_traffic_alphafolder_path: str = load_folder_path + '/' + 'predicted_traffic' + '/' + 'alpha' + str(ALPHA_PERCENT)

# Do not create patent folder 'generated_traffic_data' again
Path(load_folder_path).mkdir(parents=True, exist_ok=True)
Path(actual_traffic_folder_path).mkdir(parents=True, exist_ok=True)
Path(predicted_traffic_folder_path).mkdir(parents=True, exist_ok=True)
Path(predicted_traffic_alphafolder_path).mkdir(parents=True, exist_ok=True)

In [3]:
generate_traffic_based_on_seattle(
    from_date=FROM_DATE, 
    to_date=TO_DATE, 
    first_erlang=LAMBDA_0, 
    constant_bitrate=IS_CONSTANT_BITRATE, 
    aggregation=AGGREGATION, 
    resampling=RESAMPLING,
    actual_traffic_folder_path=actual_traffic_folder_path)

In [4]:
# generated_traffic_combined

,current_global_time,source_id,destination_id,datarate,arrival_time,departure_time
0,0.000000,9,4,100,0.000000,0.372134
1,0.003140,12,0,100,0.003140,0.516324
2,0.009222,13,6,100,0.009222,2.475916
3,0.009460,2,4,100,0.009460,1.537206
4,0.010552,9,10,100,0.010552,0.327817
...,...,...,...,...,...,...
70656967,5481.025402,1,8,100,5481.025402,5481.141680
70656968,5481.025416,8,11,100,5481.025416,5481.436566
70656969,5481.025448,12,5,100,5481.025448,5481.441730
70656970,5481.025565,13,8,100,5481.025565,5481.613195
70656971,5481.025597,11,4,100,5481.025597,5481.214484

In [5]:
# generated_traffic = divide_generated_traffic_into_periods(generated_traffic_combined,UPGRADE_PERIOD)

In [6]:
# generated_traffic[0]

,current_global_time,source_id,destination_id,datarate,arrival_time,departure_time
0,0.000000,9,4,100,0.000000,0.372134
1,0.003140,12,0,100,0.003140,0.516324
2,0.009222,13,6,100,0.009222,2.475916
3,0.009460,2,4,100,0.009460,1.537206
4,0.010552,9,10,100,0.010552,0.327817
...,...,...,...,...,...,...
36778,89.986408,9,7,100,89.986408,90.378965
36779,89.995635,6,7,100,89.995635,91.094515
36780,89.996583,9,11,100,89.996583,92.024534
36781,89.996733,12,1,100,89.996733,92.004184
36782,89.996829,11,0,100,89.996829,90.883217

In [7]:
# draw_generated_traffic(generated_traffic_combined)
# draw_erlangs_from_Seattle(
#     from_date=FROM_DATE, 
#     to_date=TO_DATE, 
#     first_erlang=LAMBDA_0, 
#     aggregation=AGGREGATION, 
#     resampling=RESAMPLING)

In [8]:
# predicted_traffic = perdict_traffic(
#     generated_traffic=generated_traffic_combined,
#     constant_bitrate=IS_CONSTANT_BITRATE, 
#     period_length=UPGRADE_PERIOD, 
#     alpha=ALPHA_PERCENT)

In [9]:
# draw_generated_traffic(pd.concat(predicted_traffic))

In [10]:
# draw_generated_traffic(divide_generated_traffic_into_periods(generated_traffic_combined,UPGRADE_PERIOD)[3])
# draw_generated_traffic(predicted_traffic[2])

In [11]:
# type(generated_traffic)

list

In [12]:
# type(generated_traffic[0])

pandas.core.frame.DataFrame

In [13]:
# len(generated_traffic)

61

In [14]:
# type(predicted_traffic)

list

In [15]:
# type(predicted_traffic[0])

pandas.core.frame.DataFrame

In [16]:
# len(predicted_traffic)

61

In [17]:
# generated_traffic[-1]

,current_global_time,source_id,destination_id,datarate,arrival_time,departure_time
67180597,5400.000032,3,6,100,5400.000032,5400.418765
67180598,5400.000183,2,3,100,5400.000183,5401.036248
67180599,5400.000185,13,6,100,5400.000185,5400.283040
67180600,5400.000215,11,3,100,5400.000215,5408.672488
67180601,5400.000255,6,12,100,5400.000255,5401.131483
...,...,...,...,...,...,...
70656967,5481.025402,1,8,100,5481.025402,5481.141680
70656968,5481.025416,8,11,100,5481.025416,5481.436566
70656969,5481.025448,12,5,100,5481.025448,5481.441730
70656970,5481.025565,13,8,100,5481.025565,5481.613195
70656971,5481.025597,11,4,100,5481.025597,5481.214484

In [18]:
# predicted_traffic[0].iloc[len(predicted_traffic)]

current_global_time     90.147564
source_id               13.000000
destination_id          10.000000
datarate               100.000000
arrival_time            90.147564
departure_time          91.170153
Name: 61, dtype: float64

In [19]:
# from pathlib import Path

# parent_folder: str = 'generated_traffic_data'
# load_folder_path: str = parent_folder + '/' + 'load' + '_' + str(LAMBDA_0)
# actual_traffic_folder_path: str = load_folder_path + '/' + 'actual_traffic'
# predicted_traffic_folder_path: str = load_folder_path + '/' + 'predicted_traffic'
# predicted_traffic_alphafolder_path: str = load_folder_path + '/' + 'predicted_traffic' + '/' + 'alpha' + str(ALPHA_PERCENT)

# # Do not create patent folder 'generated_traffic_data' again
# Path(load_folder_path).mkdir(parents=True, exist_ok=True)
# Path(actual_traffic_folder_path).mkdir(parents=True, exist_ok=True)
# Path(predicted_traffic_folder_path).mkdir(parents=True, exist_ok=True)
# Path(predicted_traffic_alphafolder_path).mkdir(parents=True, exist_ok=True)

In [20]:
# generated_traffic

[       current_global_time  source_id  destination_id  datarate  arrival_time  \
 0                 0.000000          9               4       100      0.000000
 1                 0.003140         12               0       100      0.003140
 2                 0.009222         13               6       100      0.009222
 3                 0.009460          2               4       100      0.009460
 4                 0.010552          9              10       100      0.010552
 ...                    ...        ...             ...       ...           ...
 36778            89.986408          9               7       100     89.986408
 36779            89.995635          6               7       100     89.995635
 36780            89.996583          9              11       100     89.996583
 36781            89.996733         12               1       100     89.996733
 36782            89.996829         11               0       100     89.996829

        departure_time
 0            0.372134
 1            0.516324
 2            2.475916
 3            1.537206
 4            0.327817
 ...               ...
 36778       90.378965
 36779       91.094515
 36780       92.024534
 36781       92.004184
 36782       90.883217

 [36783 rows x 6 columns],
        current_global_time  source_id  destination_id  datarate  arrival_time  \
 36783            90.000217         10               9       100     90.000217
 36784            90.001655          4               9       100     90.001655
 36785            90.003391          6              13       100     90.003391
 36786            90.008504          0               1       100     90.008504
 36787            90.023321          6              12       100     90.023321
 ...                    ...        ...             ...       ...           ...
 79577           179.995183          7               3       100    179.995183
 79578           179.995838         11              10       100    179.995838
 79579           179.996130         13               8       100    179.996130
 79580           179.998706          1               3       100    179.998706
 79581           179.999110         13               5       100    179.999110

        departure_time
 36783       90.091484
 36784       90.593664
 36785       91.843973
 36786       92.504950
 36787       91.424145
 ...               ...
 79577      180.915398
 79578      180.992411
 79579      180.284726
 79580      180.864387
 79581      180.781672

 [42799 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 79582            180.001524          5              13       100
 79583            180.002971          4              12       100
 79584            180.005938          5               0       100
 79585            180.007846         12              11       100
 79586            180.008307         13               3       100
 ...                     ...        ...             ...       ...
 126579           269.990830          7              12       100
 126580           269.992354         13               5       100
 126581           269.993179          6               9       100
 126582           269.995596          2               0       100
 126583           269.998018         11               5       100

         arrival_time  departure_time
 79582     180.001524      180.337351
 79583     180.002971      180.151375
 79584     180.005938      180.482983
 79585     180.007846      181.271848
 79586     180.008307      180.453834
 ...              ...             ...
 126579    269.990830      270.765788
 126580    269.992354      270.680332
 126581    269.993179      273.876313
 126582    269.995596      271.164540
 126583    269.998018      270.379764

 [47002 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 126584           270.000160          9               0       100
 126585           270.001933          2              11       100
 126586           270.003662          0               7       100
 126587           270.004784         10               8       100
 126588           270.005515          1               0       100
 ...                     ...        ...             ...       ...
 183311           359.993326          3              13       100
 183312           359.994531          0               9       100
 183313           359.996244         13               5       100
 183314           359.999395          8               9       100
 183315           359.999604          6              13       100

         arrival_time  departure_time
 126584    270.000160      270.036947
 126585    270.001933      270.009487
 126586    270.003662      270.019900
 126587    270.004784      270.590585
 126588    270.005515      270.160255
 ...              ...             ...
 183311    359.993326      363.462283
 183312    359.994531      360.474395
 183313    359.996244      360.844843
 183314    359.999395      360.953007
 183315    359.999604      360.585146

 [56732 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 183316           360.001035         10              13       100
 183317           360.001298          0               8       100
 183318           360.002849          2               4       100
 183319           360.004662          9               0       100
 183320           360.006276         10               8       100
 ...                     ...        ...             ...       ...
 246846           449.993390         13              10       100
 246847           449.993739          6               2       100
 246848           449.994245         10               2       100
 246849           449.994792          8               3       100
 246850           449.997845          4               5       100

         arrival_time  departure_time
 183316    360.001035      361.096945
 183317    360.001298      360.219255
 183318    360.002849      360.469800
 183319    360.004662      361.908415
 183320    360.006276      360.420701
 ...              ...             ...
 246846    449.993390      450.954302
 246847    449.993739      450.161019
 246848    449.994245      452.567011
 246849    449.994792      453.001111
 246850    449.997845      451.048104

 [63535 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 246851           450.001037         11              10       100
 246852           450.001991         13              10       100
 246853           450.008561          1               5       100
 246854           450.008985          4              13       100
 246855           450.009251          4               3       100
 ...                     ...        ...             ...       ...
 317870           539.994194          2               8       100
 317871           539.997530          8              13       100
 317872           539.998050          8              11       100
 317873           539.998398          1              11       100
 317874           539.999892         13               4       100

         arrival_time  departure_time
 246851    450.001037      450.374181
 246852    450.001991      454.760765
 246853    450.008561      450.077645
 246854    450.008985      451.757427
 246855    450.009251      450.215651
 ...              ...             ...
 317870    539.994194      541.117787
 317871    539.997530      540.506206
 317872    539.998050      540.717421
 317873    539.998398      540.870525
 317874    539.999892      540.018790

 [71024 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 317875           540.000438         13               3       100
 317876           540.004237          2               3       100
 317877           540.005350         11               8       100
 317878           540.006199         11               4       100
 317879           540.009127          3               5       100
 ...                     ...        ...             ...       ...
 392528           629.995115          4              13       100
 392529           629.996564          8              12       100
 392530           629.997638         13               0       100
 392531           629.998788         10               6       100
 392532           629.998986          8               0       100

         arrival_time  departure_time
 317875    540.000438      541.235277
 317876    540.004237      540.296218
 317877    540.005350      540.484540
 317878    540.006199      540.406965
 317879    540.009127      541.294649
 ...              ...             ...
 392528    629.995115      631.454325
 392529    629.996564      632.788655
 392530    629.997638      633.385090
 392531    629.998788      630.189186
 392532    629.998986      631.403242

 [74658 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 392533           630.002827          4               5       100
 392534           630.003098          8              12       100
 392535           630.004869          1               5       100
 392536           630.004988          9               4       100
 392537           630.005684         13              11       100
 ...                     ...        ...             ...       ...
 480172           719.994429         11               2       100
 480173           719.994508          0               3       100
 480174           719.994900          6               1       100
 480175           719.994943         11               4       100
 480176           719.997718          4               7       100

         arrival_time  departure_time
 392533    630.002827      630.452382
 392534    630.003098      630.102975
 392535    630.004869      632.474715
 392536    630.004988      630.368417
 392537    630.005684      630.722909
 ...              ...             ...
 480172    719.994429      723.732453
 480173    719.994508      722.272700
 480174    719.994900      720.625722
 480175    719.994943      720.423395
 480176    719.997718      722.179608

 [87644 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 480177           720.000246          7              12       100
 480178           720.001079         12               9       100
 480179           720.001340          8               4       100
 480180           720.002387          4               7       100
 480181           720.002534          9              12       100
 ...                     ...        ...             ...       ...
 576646           809.998230         12               9       100
 576647           809.998965          4               7       100
 576648           809.999517          0               9       100
 576649           809.999664          2               7       100
 576650           809.999863          5               3       100

         arrival_time  departure_time
 480177    720.000246      720.408070
 480178    720.001079      720.834917
 480179    720.001340      721.081980
 480180    720.002387      720.561510
 480181    720.002534      720.024163
 ...              ...             ...
 576646    809.998230      810.339925
 576647    809.998965      810.134671
 576648    809.999517      810.933249
 576649    809.999664      810.525450
 576650    809.999863      810.974464

 [96474 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 576651           810.000150          0              12       100
 576652           810.001357          6              13       100
 576653           810.003225         13               6       100
 576654           810.005906         12              11       100
 576655           810.006541          0               6       100
 ...                     ...        ...             ...       ...
 691660           899.995684          1              11       100
 691661           899.996965          9               4       100
 691662           899.997543          5               3       100
 691663           899.998715         12               9       100
 691664           899.999016          1               4       100

         arrival_time  departure_time
 576651    810.000150      813.068128
 576652    810.001357      810.074362
 576653    810.003225      810.598591
 576654    810.005906      810.090791
 576655    810.006541      810.131418
 ...              ...             ...
 691660    899.995684      900.439733
 691661    899.996965      903.195553
 691662    899.997543      902.094845
 691663    899.998715      900.558160
 691664    899.999016      902.050388

 [115014 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 691665           900.000884         10              12       100
 691666           900.000989          9               1       100
 691667           900.001561          5              13       100
 691668           900.002257          9               2       100
 691669           900.005411         11               4       100
 ...                     ...        ...             ...       ...
 817299           989.994920          0              11       100
 817300           989.996290          4               6       100
 817301           989.996589          4               6       100
 817302           989.997567          5               4       100
 817303           989.999483         12               2       100

         arrival_time  departure_time
 691665    900.000884      900.231649
 691666    900.000989      901.275289
 691667    900.001561      901.212416
 691668    900.002257      900.161770
 691669    900.005411      901.257569
 ...              ...             ...
 817299    989.994920      990.978440
 817300    989.996290      991.593057
 817301    989.996589      990.717719
 817302    989.997567      990.671575
 817303    989.999483      992.069208

 [125639 rows x 6 columns],
         current_global_time  source_id  destination_id  datarate  \
 817304           990.000123          6               5       100
 817305           990.000455          5               4       100
 817306           990.001776          9              11       100
 817307           990.001979         12               0       100
 817308           990.002551          8               4       100
 ...                     ...        ...             ...       ...
 938010          1079.996842          2               7       100
 938011          1079.997548          1               4       100
 938012          1079.998773          0               7       100
 938013          1079.998848          8              13       100
 938014          1079.999183          1               5       100

         arrival_time  departure_time
 817304    990.000123      990.187905
 817305    990.000455      990.180464
 817306    990.001776      990.743744
 817307    990.001979      992.262306
 817308    990.002551      990.361394
 ...              ...             ...
 938010   1079.996842     1080.281796
 938011   1079.997548     1080.458434
 938012   1079.998773     1080.692432
 938013   1079.998848     1080.002723
 938014   1079.999183     1080.848345

 [120711 rows x 6 columns],
          current_global_time  source_id  destination_id  datarate  \
 938015           1080.000341         10              12       100
 938016           1080.001262          5               9       100
 938017           1080.002411          1               2       100
 938018           1080.002645          9              13       100
 938019           1080.003791         12               3       100
 ...                      ...        ...             ...       ...
 1071011          1169.998009          4              12       100
 1071012          1169.998298          7               0       100
 1071013          1169.998819          6              13       100
 1071014          1169.999373          4               7       100
 1071015          1169.999473          8               9       100

          arrival_time  departure_time
 938015    1080.000341     1081.610499
 938016    1080.001262     1081.057948
 938017    1080.002411     1080.092860
 938018    1080.002645     1080.011455
 938019    1080.003791     1080.520516
 ...               ...             ...
 1071011   1169.998009     1171.064422
 1071012   1169.998298     1171.747112
 1071013   1169.998819     1171.176357
 1071014   1169.999373     1170.071455
 1071015   1169.999473     1172.972042

 [133001 rows x 6 columns],
          current_global_time  source_id  destination_id  datarate  \
 1071016          1170.000147          5               6       100
 1071017          1170.000864         13               4       100
 1071018          1170.001157          4              13       100
 1071019          1170.001775          6               5       100
 1071020          1170.002950         10               3       100
 ...                      ...        ...             ...       ...
 1205138          1259.995125          1              11       100
 1205139          1259.995666         11               2       100
 1205140          1259.998806         11               8       100
 1205141          1259.999258          1               7       100
 1205142          1259.999309          3              11       100

          arrival_time  departure_time
 1071016   1170.000147     1170.642649
 1071017   1170.000864     1172.143188
 1071018   1170.001157     1172.542428
 1071019   1170.001775     1170.783114
 1071020   1170.002950     1170.254372
 ...               ...             ...
 1205138   1259.995125     1262.267354
 1205139   1259.995666     1260.647474
 1205140   1259.998806     1260.502797
 1205141   1259.999258     1261.770180
 1205142   1259.999309     1260.064777

 [134127 rows x 6 columns],
          current_global_time  source_id  destination_id  datarate  \
 1205143          1260.000431          6               9       100
 1205144          1260.001145          6              10       100
 1205145          1260.001237          8              10       100
 1205146          1260.001313          2               6       100
 1205147          1260.001318          6              10       100
 ...                      ...        ...             ...       ...
 1327921          1349.995486          5               7       100
 1327922          1349.995990          7              12       100
 1327923          1349.997887          6              12       100
 1327924          1349.998258          8              11       100
 1327925          1349.999858          7               6       100

          arrival_time  departure_time
 1205143   1260.000431     1260.661159
 1205144   1260.001145     1261.392077
 1205145   1260.001237     1260.341209
 1205146   1260.001313     1260.574903
 1205147   1260.001318     1261.585913
 ...               ...             ...
 1327921   1349.995486     1350.661147
 1327922   1349.995990     1351.171902
 1327923   1349.997887     1350.540957
 1327924   1349.998258     1350.180735
 1327925   1349.999858     1350.055468

 [122783 rows x 6 columns],
          current_global_time  source_id  destination_id  datarate  \
 1327926          1350.000807          1              12       100
 1327927          1350.000977          1               5       100
 1327928          1350.001275          3               1       100
 1327929          1350.001776          7               6       100
 1327930          1350.004834          3               4       100
 ...                      ...        ...             ...       ...
 1503996          1439.997121         10               9       100
 1503997          1439.998717         10               6       100
 1503998          1439.998892         13               2       100
 1503999          1439.999520          4               3       100

In [21]:
# # Save generated Traffic
# for index, traffic_dataframe in enumerate(generated_traffic):
#     #specify path for export
#     filepath: str = actual_traffic_folder_path + '/' + 'actual_traffic' + '_' + str(UPGRADE_PERIOD * index) + '_' + str(UPGRADE_PERIOD * (index + 1)) + '.txt'

#     #export DataFrame to text file
#     with open(filepath, 'w') as f:
#         df_string = traffic_dataframe.to_string(header=False, index=True)
#         f.write(df_string)

In [22]:
# # Save predicted Traffic
# for index, traffic_dataframe in enumerate(predicted_traffic):
#     #specify path for export
#     filepath: str = predicted_traffic_alphafolder_path + '/' + 'predicted_traffic' + '_' + str(UPGRADE_PERIOD * (index + 1)) + '_' + str(UPGRADE_PERIOD * (index + 2)) + '.txt'

#     #export DataFrame to text file
#     with open(filepath, 'w') as f:
#         df_string = traffic_dataframe.to_string(header=False, index=True)
#         f.write(df_string)